# Service Port
server:
  port: 8089

spring:
  # VIEW
  mvc:
    view:
      #prefix: /WEB-INF/views/
      suffix: .html

  #파일 업로드
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: c://temp//spring_uploaded_files

  # DB
  datasource:
    driver-calass-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@54.180.8.49/xe
    username: apimaster
    password: 0609

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: oracle
      database-platform: org.hibernate.dialect.OracleDialect
      generate-ddl: true

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

# Logging Setting
logging:
  level:
    org:
      hibernate: debug
    root: info