
spring:
  #파일 업로드
  servlet:
    multipart:
      location: c://temp//spring_uploaded_files

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      database: oracle
      database-platform: org.hibernate.dialect.OracleDialect
      generate-ddl: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update

    open-in-view: true