# Service Port
server:
  port: 8080

spring:

  profiles:
   # active: dev
   # active: local
    active: prod

  #파일 업로드
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # DB
  datasource:
    driver-calass-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@54.180.8.49:1521:XE
    username: apimaster
    password: 0609

# Logging Setting
logging:
  level:
    org:
      hibernate: debug
    root: info